# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_6/bd_4bad_c_shift_ram_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4bad_c_shift_ram_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_6/bd_4bad_c_shift_ram_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4bad_c_shift_ram_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
