# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/MIZ7035.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_gig_ethernet_pcs_pma_0_0/system_gig_ethernet_pcs_pma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gig_ethernet_pcs_pma_0_0 || ORIG_REF_NAME==system_gig_ethernet_pcs_pma_0_0}]

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0}]

# IP: bd/system/ip/system_xlconstant_0_1/system_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_1 || ORIG_REF_NAME==system_xlconstant_0_1}]

# IP: bd/system/ip/system_xlconstant_1_0/system_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_1_0 || ORIG_REF_NAME==system_xlconstant_1_0}]

# IP: bd/system/ip/system_util_vector_logic_0_0/system_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_0_0 || ORIG_REF_NAME==system_util_vector_logic_0_0}]

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_gig_ethernet_pcs_pma_0_0/system_gig_ethernet_pcs_pma_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_gig_ethernet_pcs_pma_0_0 || ORIG_REF_NAME==system_gig_ethernet_pcs_pma_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_gig_ethernet_pcs_pma_0_0/synth/system_gig_ethernet_pcs_pma_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_gig_ethernet_pcs_pma_0_0 || ORIG_REF_NAME==system_gig_ethernet_pcs_pma_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_gig_ethernet_pcs_pma_0_0/synth/system_gig_ethernet_pcs_pma_0_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
