# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z035ffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.cache/wt [current_project]
set_property parent.project_path F:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib F:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/imports/hdl/system_wrapper.v
add_files F:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all f:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_gig_ethernet_pcs_pma_0_0/system_gig_ethernet_pcs_pma_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_gig_ethernet_pcs_pma_0_0/synth/system_gig_ethernet_pcs_pma_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_gig_ethernet_pcs_pma_0_0/synth/system_gig_ethernet_pcs_pma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files F:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/system.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.srcs/constrs_1/new/MIZ7035.xdc
set_property used_in_implementation false [get_files F:/FPGA_project/vivado/miz7035/lwip_sfp/Miz_sys/Miz_sys.srcs/constrs_1/new/MIZ7035.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z035ffg676-2


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
