# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/MIZ_SOC/CH14_AXI_OLED/AXI_OLED/AXI_OLED/AXI_OLED.cache/wt [current_project]
set_property parent.project_path D:/MIZ_SOC/CH14_AXI_OLED/AXI_OLED/AXI_OLED/AXI_OLED.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files d:/MIZ_SOC/CH14_AXI_OLED/AXI_OLED/IPSRC/charLib/charLib.coe
add_files -quiet D:/MIZ_SOC/CH14_AXI_OLED/AXI_OLED/AXI_OLED/AXI_OLED.runs/charLib_synth_1/charLib.dcp
set_property used_in_implementation false [get_files D:/MIZ_SOC/CH14_AXI_OLED/AXI_OLED/AXI_OLED/AXI_OLED.runs/charLib_synth_1/charLib.dcp]
read_verilog -library xil_defaultlib {
  D:/MIZ_SOC/CH14_AXI_OLED/AXI_OLED/IPSRC/SpiCtrl.v
  D:/MIZ_SOC/CH14_AXI_OLED/AXI_OLED/IPSRC/Delay.v
  D:/MIZ_SOC/CH14_AXI_OLED/AXI_OLED/IPSRC/SSD1306_OLED_v1_0_S00_AXI.v
  D:/MIZ_SOC/CH14_AXI_OLED/AXI_OLED/IPSRC/SSD1306_OLED_ML.v
}
synth_design -top SSD1306_OLED_ML -part xc7z010clg400-1
write_checkpoint -noxdef SSD1306_OLED_ML.dcp
catch { report_utilization -file SSD1306_OLED_ML_utilization_synth.rpt -pb SSD1306_OLED_ML_utilization_synth.pb }
