# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FILE/FPGA/ZYNQ/08_LAN/05_LWIP_1g_sfp/example/LWIP_sfp/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_gig_ethernet_pcs_pma_0_0/system_gig_ethernet_pcs_pma_0_0.xci
# IP: The module: 'system_gig_ethernet_pcs_pma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/05_LWIP_1g_sfp/example/LWIP_sfp/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_gig_ethernet_pcs_pma_0_0/system_gig_ethernet_pcs_pma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/05_LWIP_1g_sfp/example/LWIP_sfp/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_gig_ethernet_pcs_pma_0_0/synth/system_gig_ethernet_pcs_pma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/05_LWIP_1g_sfp/example/LWIP_sfp/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_gig_ethernet_pcs_pma_0_0/synth/system_gig_ethernet_pcs_pma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/FILE/FPGA/ZYNQ/08_LAN/05_LWIP_1g_sfp/example/LWIP_sfp/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_gig_ethernet_pcs_pma_0_0/system_gig_ethernet_pcs_pma_0_0.xci
# IP: The module: 'system_gig_ethernet_pcs_pma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/05_LWIP_1g_sfp/example/LWIP_sfp/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_gig_ethernet_pcs_pma_0_0/system_gig_ethernet_pcs_pma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/05_LWIP_1g_sfp/example/LWIP_sfp/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_gig_ethernet_pcs_pma_0_0/synth/system_gig_ethernet_pcs_pma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/05_LWIP_1g_sfp/example/LWIP_sfp/lwip_sfp/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_gig_ethernet_pcs_pma_0_0/synth/system_gig_ethernet_pcs_pma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
