# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FILE/FPGA/ZYNQ/08_LAN/05_MB_DDR3_LWIP_RGMII/02_PL_AXI_LWIP_RGMII/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_auto_pc_1_1/system_auto_pc_1.xci
# IP: The module: 'system_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/05_MB_DDR3_LWIP_RGMII/02_PL_AXI_LWIP_RGMII/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_auto_pc_1_1/system_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/FILE/FPGA/ZYNQ/08_LAN/05_MB_DDR3_LWIP_RGMII/02_PL_AXI_LWIP_RGMII/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_auto_pc_1_1/system_auto_pc_1.xci
# IP: The module: 'system_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/05_MB_DDR3_LWIP_RGMII/02_PL_AXI_LWIP_RGMII/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_auto_pc_1_1/system_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
