# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_AX7204/19 ethernet_test_1g_100m/rgmii_ethernet/eth_test.srcs/sources_1/ip/clk_ref/clk_ref.xci
# IP: The module: 'clk_ref' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_AX7204/19 ethernet_test_1g_100m/rgmii_ethernet/eth_test.srcs/sources_1/ip/clk_ref/clk_ref_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_AX7204/19 ethernet_test_1g_100m/rgmii_ethernet/eth_test.srcs/sources_1/ip/clk_ref/clk_ref.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_AX7204/19 ethernet_test_1g_100m/rgmii_ethernet/eth_test.srcs/sources_1/ip/clk_ref/clk_ref_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/demo_AX7204/19 ethernet_test_1g_100m/rgmii_ethernet/eth_test.srcs/sources_1/ip/clk_ref/clk_ref.xci
# IP: The module: 'clk_ref' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_AX7204/19 ethernet_test_1g_100m/rgmii_ethernet/eth_test.srcs/sources_1/ip/clk_ref/clk_ref_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_AX7204/19 ethernet_test_1g_100m/rgmii_ethernet/eth_test.srcs/sources_1/ip/clk_ref/clk_ref.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_AX7204/19 ethernet_test_1g_100m/rgmii_ethernet/eth_test.srcs/sources_1/ip/clk_ref/clk_ref_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
