# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/system_axi_ethernet_0_0.xci
# IP: The module: 'system_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/bd_4bad.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad || ORIG_REF_NAME==bd_4bad} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_0/bd_4bad_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_eth_buf_0 || ORIG_REF_NAME==bd_4bad_eth_buf_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_1/bd_4bad_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_mac_0 || ORIG_REF_NAME==bd_4bad_mac_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_2/bd_4bad_pcs_pma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_pcs_pma_0 || ORIG_REF_NAME==bd_4bad_pcs_pma_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_3/bd_4bad_xlconstant_phyadd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_xlconstant_phyadd_0 || ORIG_REF_NAME==bd_4bad_xlconstant_phyadd_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_4/bd_4bad_xlconstant_config_vec_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_xlconstant_config_vec_0 || ORIG_REF_NAME==bd_4bad_xlconstant_config_vec_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_5/bd_4bad_xlconstant_config_val_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_xlconstant_config_val_0 || ORIG_REF_NAME==bd_4bad_xlconstant_config_val_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_6/bd_4bad_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_c_shift_ram_0_0 || ORIG_REF_NAME==bd_4bad_c_shift_ram_0_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_7/bd_4bad_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_c_counter_binary_0_0 || ORIG_REF_NAME==bd_4bad_c_counter_binary_0_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_8/bd_4bad_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_xlconstant_0_0 || ORIG_REF_NAME==bd_4bad_xlconstant_0_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_9/bd_4bad_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_util_vector_logic_0_0 || ORIG_REF_NAME==bd_4bad_util_vector_logic_0_0} -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/system_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/synth/system_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/bd_4bad_ooc.xdc

# IP: F:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/system_axi_ethernet_0_0.xci
# IP: The module: 'system_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/bd_4bad.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad || ORIG_REF_NAME==bd_4bad} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_0/bd_4bad_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_eth_buf_0 || ORIG_REF_NAME==bd_4bad_eth_buf_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_1/bd_4bad_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_mac_0 || ORIG_REF_NAME==bd_4bad_mac_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_2/bd_4bad_pcs_pma_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_pcs_pma_0 || ORIG_REF_NAME==bd_4bad_pcs_pma_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_3/bd_4bad_xlconstant_phyadd_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_xlconstant_phyadd_0 || ORIG_REF_NAME==bd_4bad_xlconstant_phyadd_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_4/bd_4bad_xlconstant_config_vec_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_xlconstant_config_vec_0 || ORIG_REF_NAME==bd_4bad_xlconstant_config_vec_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_5/bd_4bad_xlconstant_config_val_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_xlconstant_config_val_0 || ORIG_REF_NAME==bd_4bad_xlconstant_config_val_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_6/bd_4bad_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_c_shift_ram_0_0 || ORIG_REF_NAME==bd_4bad_c_shift_ram_0_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_7/bd_4bad_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_c_counter_binary_0_0 || ORIG_REF_NAME==bd_4bad_c_counter_binary_0_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_8/bd_4bad_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_xlconstant_0_0 || ORIG_REF_NAME==bd_4bad_xlconstant_0_0} -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_9/bd_4bad_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4bad_util_vector_logic_0_0 || ORIG_REF_NAME==bd_4bad_util_vector_logic_0_0} -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/system_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/synth/system_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FILE/FPGA/ZYNQ/08_LAN/02_LWIP_RGMII/02_LWIP_RGMII.srcs/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/bd_4bad_ooc.xdc
