webtalk_init -webtalk_dir F:/FPGA_project/vivado/kc705/udp_ip/udp_ip.sim/sim_1/behav/xsim.dir/sim_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 05 21:04:53 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "674e9dca-51f0-48f0-b087-66ed3ecf7d94" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3a51d336a1e54702a6f9ff71ffacd0c5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Pentium(R) CPU B980 @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.92_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "28796_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2669309977 -regid "" -xml F:/FPGA_project/vivado/kc705/udp_ip/udp_ip.sim/sim_1/behav/xsim.dir/sim_top_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/FPGA_project/vivado/kc705/udp_ip/udp_ip.sim/sim_1/behav/xsim.dir/sim_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/FPGA_project/vivado/kc705/udp_ip/udp_ip.sim/sim_1/behav/xsim.dir/sim_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
