# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/DS_SRC/MIA701/aurora_test/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/ila_7series/ila_7series.xci
# IP: The module: 'ila_7series' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/DS_SRC/MIA701/aurora_test/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/ila_7series/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_7series'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/DS_SRC/MIA701/aurora_test/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/ila_7series/ila_7series_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_7series'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: e:/DS_SRC/MIA701/aurora_test/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/ila_7series/ila_7series.xci
# IP: The module: 'ila_7series' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/DS_SRC/MIA701/aurora_test/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/ila_7series/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_7series'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/DS_SRC/MIA701/aurora_test/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/ila_7series/ila_7series_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_7series'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
