# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7z035ffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.cache/wt [current_project]
set_property parent.project_path F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/CRC32_check.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/CRC32_generation.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/arp_layer.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/arp_receive.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/arp_send.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/icmp_packet_process.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/icmp_packet_send.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/ip_header_checksum_check.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/ip_layer.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/ip_receive.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/ip_send.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/mac_cache.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/mac_control_frame_process.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/mac_layer.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/mac_receive.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/mac_send.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/mac_send_flow_control.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/receive_buffer.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/rgmii_receive.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/rgmii_send.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/send_buffer.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/common/tri_mode_ethernet_mac_0_reset_sync.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/udp_ip_protocol_stack.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/udp_layer.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/udp_receive.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/udp_send.v
  F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/imports/UDP_IP/udp_transmit_test.v
}
read_ip -quiet F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/mac_frame_length_fifo/mac_frame_length_fifo.xci
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/mac_frame_length_fifo/mac_frame_length_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/mac_frame_length_fifo/mac_frame_length_fifo_clocks.xdc]

read_ip -quiet F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/mac_receive_fifo/mac_receive_fifo.xci
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/mac_receive_fifo/mac_receive_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/mac_receive_fifo/mac_receive_fifo_clocks.xdc]

read_ip -quiet F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/shift_mac/shift_mac.xci

read_ip -quiet F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/mac_tx_frame_info_fifo/mac_tx_frame_info_fifo.xci
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/mac_tx_frame_info_fifo/mac_tx_frame_info_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/mac_tx_frame_info_fifo/mac_tx_frame_info_fifo_clocks.xdc]

read_ip -quiet F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/MAC_send_fifo/MAC_send_fifo.xci
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/MAC_send_fifo/MAC_send_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/MAC_send_fifo/MAC_send_fifo_clocks.xdc]

read_ip -quiet F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/shift_ip/shift_ip.xci

read_ip -quiet F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/echo_data_fifo/echo_data_fifo.xci
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/echo_data_fifo/echo_data_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/echo_data_fifo/echo_data_fifo_clocks.xdc]

read_ip -quiet F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/shift/shift.xci

read_ip -quiet F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/udp_packet_fifo/udp_packet_fifo.xci
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/udp_packet_fifo/udp_packet_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/udp_packet_fifo/udp_packet_fifo_clocks.xdc]

read_ip -quiet F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/constrs_1/new/udp_ip.xdc
set_property used_in_implementation false [get_files F:/FILE/FPGA/test/CH01_udp_ip_rgmii/udp_ip_rgmii_1ch/udp_ip.srcs/constrs_1/new/udp_ip.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top udp_transmit_test -part xc7z035ffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef udp_transmit_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file udp_transmit_test_utilization_synth.rpt -pb udp_transmit_test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
