# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7z035ffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.cache/wt [current_project]
set_property parent.project_path F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/imports/udp_ip_stack/udp_ip_protocol_stack.dcp
set_property used_in_implementation false [get_files F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/imports/udp_ip_stack/udp_ip_protocol_stack.dcp]
read_verilog -library xil_defaultlib {
  F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/imports/example/tri_mode_ethernet_mac_0_axi_lite_sm.v
  F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/imports/example/tri_mode_ethernet_mac_0_example_design_resets.v
  F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/imports/example/tri_mode_ethernet_mac_0_reset_sync.v
  F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/imports/example/tri_mode_ethernet_mac_0_sync_block.v
  F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/imports/udp_ip_1g_sfp/udp_transmit_test.v
}
read_ip -quiet F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc]

read_ip -quiet F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0.xci
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_clocks.xdc]

read_ip -quiet F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.xci

read_ip -quiet F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/axis_data_fifo_1/axis_data_fifo_1.xci

read_ip -quiet F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/axis_dwidth_converter_1/axis_dwidth_converter_1.xci

read_ip -quiet F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0.xci

read_ip -quiet F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/udp_packet_fifo/udp_packet_fifo.xci
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/udp_packet_fifo/udp_packet_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/udp_packet_fifo/udp_packet_fifo_clocks.xdc]

read_ip -quiet F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/constrs_1/new/udp_ip_1g.xdc
set_property used_in_implementation false [get_files F:/FILE/FPGA/ZYNQ/08_LAN/03_udp_ip_1g_sfp/udp_ip_1g_sfp/udp_ip_1g_sfp.srcs/constrs_1/new/udp_ip_1g.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top udp_transmit_test -part xc7z035ffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef udp_transmit_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file udp_transmit_test_utilization_synth.rpt -pb udp_transmit_test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
