# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: j:/FEP/ETH1512/MZ7035/CH02_PL_AXI_ETH_RGMII/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0.xci
# IP: The module: 'system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: j:/FEP/ETH1512/MZ7035/CH02_PL_AXI_ETH_RGMII/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: j:/FEP/ETH1512/MZ7035/CH02_PL_AXI_ETH_RGMII/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0.xci
# IP: The module: 'system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: j:/FEP/ETH1512/MZ7035/CH02_PL_AXI_ETH_RGMII/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
