# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/MIA701SRC/aurora_8b10b_ex/aurora_8b10b_ex.cache/wt [current_project]
set_property parent.project_path E:/MIA701SRC/aurora_8b10b_ex/aurora_8b10b_ex.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/MIA701SRC/aurora_8b10b_ex/aurora_8b10b_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet e:/MIA701SRC/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/ila_7series/ila_7series.dcp
set_property used_in_implementation false [get_files e:/MIA701SRC/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/ila_7series/ila_7series.dcp]
add_files -quiet e:/MIA701SRC/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/vio_7series/vio_7series.dcp
set_property used_in_implementation false [get_files e:/MIA701SRC/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/vio_7series/vio_7series.dcp]
read_verilog -library xil_defaultlib {
  E:/MIA701SRC/aurora_8b10b_ex/imports/aurora_8b10b_axi_to_ll_exdes.v
  E:/MIA701SRC/aurora_8b10b_ex/imports/aurora_8b10b_ll_to_axi_exdes.v
  E:/MIA701SRC/aurora_8b10b_ex/imports/aurora_8b10b_cdc_sync_exdes.v
  E:/MIA701SRC/aurora_8b10b_ex/imports/aurora_8b10b_frame_check.v
  E:/MIA701SRC/aurora_8b10b_ex/imports/aurora_8b10b_frame_gen.v
  E:/MIA701SRC/aurora_8b10b_ex/imports/aurora_8b10b_exdes.v
}
read_ip -quiet E:/MIA701SRC/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/aurora_8b10b/aurora_8b10b.xci
set_property used_in_implementation false [get_files -all e:/MIA701SRC/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/aurora_8b10b/aurora_8b10b_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/MIA701SRC/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/aurora_8b10b/aurora_8b10b_ooc.xdc]
set_property is_locked true [get_files E:/MIA701SRC/aurora_8b10b_ex/aurora_8b10b_ex.srcs/sources_1/ip/aurora_8b10b/aurora_8b10b.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/MIA701SRC/aurora_8b10b_ex/imports/aurora_8b10b_exdes.xdc
set_property used_in_implementation false [get_files E:/MIA701SRC/aurora_8b10b_ex/imports/aurora_8b10b_exdes.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top aurora_8b10b_exdes -part xc7a100tfgg484-2


write_checkpoint -force -noxdef aurora_8b10b_exdes.dcp

catch { report_utilization -file aurora_8b10b_exdes_utilization_synth.rpt -pb aurora_8b10b_exdes_utilization_synth.pb }
