# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/MIA701SRC/aurora_8b10b_ex/imports/aurora_8b10b_exdes.xdc

# IP: ip/aurora_8b10b/aurora_8b10b.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aurora_8b10b || ORIG_REF_NAME==aurora_8b10b}]
