webtalk_init -webtalk_dir J:\\FEP\\ETH1512\\MZ7035\\CH01_EMIO_ETH_RGMII\\Miz_sys\\Miz_sys.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-07-19 15:34:57" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "135256_15690819_210558907_628" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "q7hj65cvav2ne43i7ruu17aoe0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_122" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "122" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4008 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.130 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1531984624702" -context "sdk\\\\hardware/1531984624702"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1531984624702"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1531984624702"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1531984624702"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1531984624702"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1531984624702"
webtalk_add_data -client sdk -key Device -value "7z035" -context "sdk\\\\hardware/1531984624702"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1531984624702"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1531984624702"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1531984624702"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1531984624702"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1531985697044"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1531985697044"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1531985697044"
webtalk_add_data -client sdk -key DebugCount -value "3" -context "sdk\\\\bsp/1531985697044"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1531985697044"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1531985697044"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1531985697044"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1531985697044"
webtalk_transmit -clientid 1156967266 -regid "135256_15690819_210558907_628" -xml J:\\FEP\\ETH1512\\MZ7035\\CH01_EMIO_ETH_RGMII\\Miz_sys\\Miz_sys.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html J:\\FEP\\ETH1512\\MZ7035\\CH01_EMIO_ETH_RGMII\\Miz_sys\\Miz_sys.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm J:\\FEP\\ETH1512\\MZ7035\\CH01_EMIO_ETH_RGMII\\Miz_sys\\Miz_sys.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
