# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/vivado_project/miz7035/ibert_1_25g/ibert_7series_gtx_0_ex/imports/example_ibert_7series_gtx_0.xdc

# IP: ip/ibert_7series_gtx_0/ibert_7series_gtx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ibert_7series_gtx_0 || ORIG_REF_NAME==ibert_7series_gtx_0}]
