set_property PACKAGE_PIN K15 [get_ports DC]
set_property PACKAGE_PIN J16 [get_ports RES]
set_property PACKAGE_PIN J18 [get_ports SCLK]
set_property PACKAGE_PIN K18 [get_ports SDIN]
set_property PACKAGE_PIN J15 [get_ports VBAT]
set_property PACKAGE_PIN J17 [get_ports VDD]
set_property IOSTANDARD LVCMOS33 [get_ports DC]
set_property IOSTANDARD LVCMOS33 [get_ports RES]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SDIN]
set_property IOSTANDARD LVCMOS33 [get_ports VBAT]
set_property IOSTANDARD LVCMOS33 [get_ports VDD]


connect_debug_port u_ila_1/probe1 [get_nets [list {system_i/axis_data_fifo_1_M_AXIS_TDATA[0]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[1]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[2]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[3]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[4]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[5]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[6]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[7]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[8]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[9]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[10]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[11]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[12]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[13]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[14]} {system_i/axis_data_fifo_1_M_AXIS_TDATA[15]}]]
connect_debug_port u_ila_1/probe2 [get_nets [list {system_i/axis_data_fifo_1_M_AXIS_TKEEP[0]} {system_i/axis_data_fifo_1_M_AXIS_TKEEP[1]}]]
connect_debug_port u_ila_1/probe3 [get_nets [list system_i/axis_data_fifo_1_M_AXIS_TLAST]]
connect_debug_port u_ila_1/probe4 [get_nets [list system_i/axis_data_fifo_1_M_AXIS_TVALID]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/S_AXIS_1_TDATA[0]} {system_i/S_AXIS_1_TDATA[1]} {system_i/S_AXIS_1_TDATA[2]} {system_i/S_AXIS_1_TDATA[3]} {system_i/S_AXIS_1_TDATA[4]} {system_i/S_AXIS_1_TDATA[5]} {system_i/S_AXIS_1_TDATA[6]} {system_i/S_AXIS_1_TDATA[7]} {system_i/S_AXIS_1_TDATA[8]} {system_i/S_AXIS_1_TDATA[9]} {system_i/S_AXIS_1_TDATA[10]} {system_i/S_AXIS_1_TDATA[11]} {system_i/S_AXIS_1_TDATA[12]} {system_i/S_AXIS_1_TDATA[13]} {system_i/S_AXIS_1_TDATA[14]} {system_i/S_AXIS_1_TDATA[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list system_i/S_AXIS_1_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list system_i/S_AXIS_1_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list system_i/S_AXIS_1_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
